# Generated by Django 2.2.5 on 2021-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('autor', models.CharField(default='', max_length=50)),
                ('edicion', models.IntegerField()),
            ],
        ),
    ]
